---
kind: Secret
apiVersion: v1
metadata:
  namespace: metallb
  name: metallb-memberlist
data:
  secretkey: "{{ .metallb.secretkey | b64enc }}"

---
kind: Secret
apiVersion: v1
metadata:
  namespace: riju
  name: registry-auth
data:
  htpasswd: "{{ .registry.htpasswd | println | b64enc }}"

---
kind: Secret
apiVersion: v1
metadata:
  namespace: riju
  name: registry-login
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "localhost:30999": {
          "username": "admin",
          "password": "{{ .registry.password }}",
          "auth": "{{ .registry.password | printf "admin:%s" | b64enc }}"
        }
      }
    }

---
kind: Secret
apiVersion: v1
metadata:
  namespace: riju-user
  name: registry-user-login
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "localhost:30999": {
          "username": "admin",
          "password": "{{ .registry.password }}",
          "auth": "{{ .registry.password | printf "admin:%s" | b64enc }}"
        }
      }
    }

---
kind: Secret
apiVersion: v1
metadata:
  namespace: riju
  name: minio-keys
stringData:
  access-key: "{{ .minio.accessKey }}"
  secret-key: "{{ .minio.secretKey }}"

---
kind: Secret
apiVersion: v1
metadata:
  namespace: riju-user
  name: minio-user-login
stringData:
  config.json: |
    {
      "version": "10",
      "aliases": {
        "riju": {
          "url": "http://minio.riju.svc",
          "accessKey": "{{ .minio.accessKey }}",
          "secretKey": "{{ .minio.secretKey }}",
          "api": "s3v4",
          "path": "auto"
        }
      }
    }
