---
kind: Namespace
apiVersion: v1
metadata:
  name: ingress-nginx

---
kind: Namespace
apiVersion: v1
metadata:
  name: cert-manager

---
kind: Namespace
apiVersion: v1
metadata:
  name: docker-registry

---
kind: Namespace
apiVersion: v1
metadata:
  name: riju-proxy

---
kind: Namespace
apiVersion: v1
metadata:
  name: riju-server

---
kind: Namespace
apiVersion: v1
metadata:
  name: user
